### PR TITLE
SQLAlchemy 1.x and 2.x compatibility: Use explicit transactions, remove sqlalchemy version constraint

### LINKED ISSUE #1785: Postgres backend fails when creating UDFs due to SQLAlchemy ROLLBACKs
### What happens?

Using the [example code from the docs](https://moj-analytical-services.github.io/splink/topic_guides/splink_fundamentals/backends/postgres.html), the following error occurs:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function datediff(date, date) does not exist
LINE 4:         SELECT (datediff(x, y)/30.4375)::float8;
                        ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: 
        CREATE OR REPLACE FUNCTION ave_months_between(x date, y date)
        RETURNS float8 AS $$
        SELECT (datediff(x, y)/30.4375)::float8;
        $$ LANGUAGE SQL IMMUTABLE;
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

When inspecting the logs, SQLAlchemy is closing connections after use causing a `ROLLBACK`:

```
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:
        CREATE OR REPLACE FUNCTION datediff(x date, y date)
        RETURNS integer AS $$
        SELECT x - y;
        $$ LANGUAGE SQL IMMUTABLE;
        
INFO:sqlalchemy.engine.Engine:[generated in 0.00009s] {}
INFO:sqlalchemy.engine.Engine:ROLLBACK
```

The linker does not use explicit transactions, so nothing is ever committed.

Note: It is possible to work around this by using the `AUTOCOMMIT` isolation level:

```
engine = engine.execution_options(isolation_level="AUTOCOMMIT")
```

### To Reproduce

Run the example code from the docs. I have added query logging here.

```
from splink.postgres.linker import PostgresLinker
from sqlalchemy import create_engine
import logging

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

# create a sqlalchemy engine to manage connecting to the database
engine = create_engine("postgresql+psycopg2://USER:PASSWORD@HOST:PORT/DB_NAME")

settings = {
    "link_type": "dedupe_only",
}

# Error is triggered by the following line.
linker = PostgresLinker("my_data_table", settings, engine=engine)
```

### OS:

iOS

### Splink version:

3.9.9

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by RobinL**
Closes #1785 and #1906 and #1786

It turns out that the UDF registration only works correctly in sqlalchemy 2.0 if you use `begin`, which starts a transaction explicitly.  otherwise subsequent function registrations can't always 'see' previous ones.

`fetchall()` no longer works in sqlalchemy 2.0.0 see **[here](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#rowproxy-is-no-longer-a-proxy-is-now-called-row-and-behaves-like-an-enhanced-named-tuple) but luckily .mappings().all() seems to work fine

I have checked, and the following work:
```
sqlalchemy.__version__='1.4.49'
pd.__version__='1.5.0'

sqlalchemy.__version__='2.0.25'
pd.__version__='1.5.0'

sqlalchemy.__version__='2.0.25'
pd.__version__='2.2.0'
```
The only combination that doesn't is:
```
sqlalchemy.__version__='1.4.49'
pd.__version__='2.2.0'

```

`AttributeError: 'Engine' object has no attribute 'cursor'`

But that's fine because https://github.com/moj-analytical-services/splink/issues/1906#issuecomment-1915508671 
>  there was no version pin for [sqlalchemy] in the pandas 1.x dependencies  so you could easily end up installing pandas 1.x and SQLAlchemy 2.x,

### CODE REVIEW

**Review by ADBond — APPROVED** [review]
This has got to pretty high up the list of lines changed to issues closed ratio!

Just a couple of things:
* looks like there is still one more reference to `.fetchall()` in `_table_exists_in_database` [here](https://github.com/moj-analytical-services/splink/blob/637a278d33ac5cc817acaed87f92b0514e31c009/splink/postgres/linker.py#L213)
* would it be possible to update the changelog?

Happy for you to merge when ready

**Comment by ADBond** [comment]
Also might be useful to fold these changes into `splink4_dev` relatively soon while it's fresh in the mind, so that the relevant changes get propagated to their correct new homes

**Comment by RobinL** [comment]
> This has got to pretty high up the list of lines changed to issues closed ratio!
> 
> Just a couple of things:
> 
> * looks like there is still one more reference to `.fetchall()` in `_table_exists_in_database` [here](https://github.com/moj-analytical-services/splink/blob/637a278d33ac5cc817acaed87f92b0514e31c009/splink/postgres/linker.py#L213)
> * would it be possible to update the changelog?
> 
> Happy for you to merge when ready

Good spots, fixed
